apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-postgres
  template:
    metadata:
     labels:
       app: consumer-postgres
    spec:
      containers:
        - image: consumer-postgres:latest
          imagePullPolicy: Never
          name: consumer-postgres-service
          ports:
            - containerPort: 8100
